### ISSUE TITLE
Prepare for PyPI Release

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon_solver_ddg_plugin#2]
- [ ] Add `version_bump.py`
- [ ] Verify `setup.py` contents
- [ ] Add GitHub automations
- [ ] Merge changes to `dev` branch
- [ ] Open version change PR
- [ ] Merge changes to `master` branch

**Comment by NeonJarbas** [comment]
https://github.com/JarbasSkills/skill-ddg/pull/8 depends on this
